// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package repo

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (thread_id, sender, content)
VALUES ($1, $2, $3)
RETURNING id, thread_id, sender, content, created_at
`

type CreateMessageParams struct {
	ThreadID int32  `json:"thread_id"`
	Sender   string `json:"sender"`
	Content  string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ThreadID, arg.Sender, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO "orders" (item,amount,number)
VALUES ($1,$2,$3)
RETURNING id, item, amount, number
`

type CreateOrderParams struct {
	Item   string `json:"item"`
	Amount string `json:"amount"`
	Number string `json:"number"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.Item, arg.Amount, arg.Number)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Item,
		&i.Amount,
		&i.Number,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO "thread" (topic)
VALUEs ($1)
RETURNING id, topic, created_at
`

func (q *Queries) CreateThread(ctx context.Context, topic string) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, topic)
	var i Thread
	err := row.Scan(&i.ID, &i.Topic, &i.CreatedAt)
	return i, err
}

const deleteMessageByID = `-- name: DeleteMessageByID :exec
DELETE FROM message
WHERE id = $1
`

func (q *Queries) DeleteMessageByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMessageByID, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, thread_id, sender, content, created_at FROM message
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesByThread = `-- name: GetMessagesByThread :many
SELECT id, thread_id, sender, content, created_at FROM message
WHERE thread_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMessagesByThread(ctx context.Context, threadID int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE message
SET content = $1
WHERE id = $2
RETURNING id, thread_id, sender, content, created_at
`

type UpdateMessageParams struct {
	Content string `json:"content"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.Content, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
